###
GET http://localhost:8080/

###

GET http://localhost:8080/users
Authorization: CAR_MANAGER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTUzMzc5OTM3MH0.-NlMtt09JY7T3SgzL56tBio9PR68b5ib2MxrhJ2D9ZvzQUOGABwRKAsxflt98scR0knSbU6TSbTg7UGyex_HNA

###

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###